[images]
  remote_images = ["https://ext.same-assets.com/*"]

[build]
  command = "bun run build"
  publish = "dist"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.12.0"
  NPM_VERSION = "10.2.0"

[dev]
  command = "bun run dev"
  port = 3000
  targetPort = 3000
  publish = "dist"
  framework = "#custom"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
